### PR TITLE
Support MKS and KSPI resources in SwitchableTanks

### PR DESCRIPTION
**Pull request by Thorbane**
Assorted tank type holds goods electronics and structural components.

Added some KSPI support as well, feel free to rename the Assorted tank type.

### CODE REVIEW

**Comment by allista** [comment]
Brilliant! I'll examine it more thoroughly and merge ASAP.
Thanks a lot!

**Comment by allista** [comment]
I've merged this onto my local development branch which is far ahead of the master, so I will close this pull request when I push the changes.

Aside from that, there are several things I want to ask about; namely:
* Why the ArgonGass is in LiquidChemicals and not in Gasses?
* Why the duplications:
    * ScrapMetal, RocketParts in Assorted and in Metal?
    * Water in LiquidChemicals and in Water?
* Why have you changed the units/L values of: LiquidFuel/Oxidizer; Waste/WasteWater and others?

I'm not a priori against these changes, I just want to know your reasoning.

**Comment by allista** [comment]
Oh, and wouldn't it be appropriate to separate Food and BioMass into a separate TANKTYPE?

**Comment by allista** [comment]
I propose the following modifications to your variant:
https://github.com/allista/hangar/blob/TankTypes-update/GameData/Hangar/TankTypes.cfg
You may leave comments on the appropriate lines there.

**Comment by Thorbane** [comment]
The Assorted tanks type should be able to hold anything that you can put into a box or bag, in essence turning the tank into a pressurized shipping crate.  I think the Metals tank should be able to hold refined materials you don't care too much about getting exposed to vacuum or bumped and jostled around.  I'm not sure why rocketparts is in Metals, I must have accidentally left it there.

If the liquid chemicals tank can hold liquid oxygen, it makes sense it can hold liquid Argon, which boils  only 3 degrees colder.

Water is in the liquid chemical tank because it's liquid.

**Comment by Thorbane** [comment]
https://docs.google.com/spreadsheets/d/1F2NYLj47O6VdThCXqBcI_hB-bDIMh4ZWB2FFyrjMLkg/edit#gid=650840806

Link to the CRP Spreadsheet.  Note that someone inverted the units/liter calculation whenever that column says it's 5.

**Comment by allista** [comment]
Oh boy, this all is so damn complex, especially when you consider the fact that changes in names and possible resources of tanks break backward compatibility =\ That accounts for the Rocket Parts in Metals.
So, basically, we may say that cryogenic tank is not needed; but than high-pressure tank for gases becomes much more expensive than implicitly cryogenic LiquidChems, and that seems a discrepancy to me. But stock KSP is full of them anyway.
Don't know what to do, actually. Can't think of a logical solution...

**Comment by allista** [comment]
I still think that Water (as it is used, as life-support resource) should not be allowed to be transported in the same tank as other liquids.

And solid karbonite? Which can be used as a fuel for turbojets and turbofans?! I shouldn't have ventured into chaotic land of resource tanks >_<

**Comment by allista** [comment]
Also densities in the spreadsheet differ from CRP configs.

**Comment by allista** [comment]
I've merged CryoStorage with LiquidChemicals, excluding gases. Please, look at the current version and tell me if you agree.

**Comment by allista** [comment]
Sorry, I couldn't wait, as I will no longer have much free time for the development in the next several weeks. So I've released it as it is.

**Comment by Thorbane** [comment]
Looks good, I put water into liquid chemicals because I figured they could wash out the tank.  And most of the water I haul around isn't for drinking, it's for fuel production.

**Comment by allista** [comment]
Does some mod provide a huge electrolysis+cryogenerator machinery to make LH2+LO2? Ah well...
Then you may just add Water there again locally and I'll do the same in the next release.

Thanks again for your help!

**Comment by Thorbane** [comment]
Is it possible to deprecate a Tank type by making it unavailable in the editor, but still defined in game for ships that already have it?

**Comment by allista** [comment]
Currently no, but it could be easily done. I've already thought about the
need for some deprecation mechanism. Great idea.

**Pull request merged**
